### ISSUE TITLE
Allocations and time on `compile` are ever-increasing

### ISSUE THREAD

**Issue by mofeing** [EnzymeAD/Reactant.jl#319]
Recently I found this strange behavior

```julia
julia> @btime Reactant.with_debug() do
           @jit Ops.abs(x)
       end
  37.419 ms (147556 allocations: 6.07 MiB)
2-element ConcreteRArray{Int64, 1}:
 1
 1

julia> @btime @jit Ops.abs(x)
  58.990 ms (297529 allocations: 12.08 MiB)
2-element ConcreteRArray{Int64, 1}:
 1
 1

julia> @btime @jit Ops.abs(x)
  74.636 ms (411819 allocations: 16.63 MiB)
2-element ConcreteRArray{Int64, 1}:
 1
 1

julia> @btime Reactant.with_debug() do
           @jit Ops.abs(x)
       end
  86.295 ms (505732 allocations: 20.37 MiB)
2-element ConcreteRArray{Int64, 1}:
 1
 1

julia> @btime Reactant.with_debug() do
           @jit Ops.abs(x)
       end
  97.753 ms (586540 allocations: 23.59 MiB)
2-element ConcreteRArray{Int64, 1}:
 1
 1

julia> @btime Reactant.with_debug() do
           @compile Ops.abs(x)
       end
  100.258 ms (652550 allocations: 26.15 MiB)

ulia> @btime @compile Ops.abs(x)
  111.832 ms (721709 allocations: 28.93 MiB)
Reactant.Compiler.Thunk{Symbol("##abs_reactant#83526")}()
```

Why are allocations (and time, but this looks like a consequence) ever increasing on each call to `compile`? For sure we are not freeing the previously compiled functions who live in the `Thunk`s but that shouldn't affect?

**Comment by glou-nes** [comment]
Got similar result as @mofeing using @jumerckx  code.
```
  91.916 ms (69670 allocations: 2.96 MiB)
  66.066 ms (148296 allocations: 6.10 MiB)
  77.496 ms (231286 allocations: 9.41 MiB)
  87.358 ms (299718 allocations: 12.15 MiB)
  97.592 ms (357958 allocations: 14.47 MiB)
  108.565 ms (416932 allocations: 16.84 MiB)
  116.130 ms (466430 allocations: 18.80 MiB)
  125.490 ms (512294 allocations: 20.63 MiB)
  133.661 ms (556702 allocations: 22.40 MiB)
  140.108 ms (603294 allocations: 24.26 MiB)
  146.170 ms (641878 allocations: 25.80 MiB)
  248.894 ms (679006 allocations: 27.28 MiB)
  166.485 ms (714678 allocations: 28.71 MiB)
```

```
Julia Version 1.11.1
Build Info:

    Note: This is an unofficial build, please report bugs to the project
    responsible for this build and not to the Julia project unless you can
    reproduce the issue using official builds available at https://julialang.org/downloads

Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 24 × 12th Gen Intel(R) Core(TM) i7-12850HX
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, alderlake)
Threads: 1 default, 0 interactive, 1 GC (on 24 virtual cores)
Environment:
  JULIA_DEPOT_PATH = ~/depot
```

**Comment by mofeing** [comment]
Allocations might be platform dependent?

I'm using macOS aarch64 (M1 pro)

**Comment by jumerckx** [comment]
> Allocations might be platform dependent?

Gaëtan and I are both on `Linux (x86_64-pc-linux-gnu)` it seems. (For me this is actually WSL, not sure about Gaëtan)

**Comment by wsmoses** [comment]
x/ref https://github.com/EnzymeAD/Enzyme.jl/issues/2152

**Comment by glou-nes** [comment]
I'm using `EndeavourOS`. I tracked allocations using `julia --track-allocations`. After several hundred calls to `@jit`.  I got this mem file:
```
./EnzymeCore/SypLX/src/rules.jl.115739.mem
     2112         return TypeVar(gensym(), Annotation{T})
     5312     tt = map(T->_annotate(Base.rewrap_unionall(T, TT0)), TT.parameters[2:end])
     1088     return ft, tt
     7808     TT = Tuple{<:FwdConfig, <:Annotation{ft}, Type{<:Annotation}, tt...}
     7808     TT = Tuple{<:RevConfig, <:Annotation{ft}, Type{<:Annotation}, tt...}
     9104     sig = Base.signature_type(f, tt)
     4896     result = Core.Compiler.findall(sig, method_table; limit=-1)
  3142144                 add_mt_backedge!(cspec, mt, sig)
```

**Comment by wsmoses** [comment]
cc @vchuravy

**Comment by wsmoses** [comment]
can you check if this persists with the recently released Enzyme.jl 0.13.19?

**Comment by avik-pal** [comment]
Seems to persist with 0.13.19

```
  100.544 ms (56143 allocations: 2.43 MiB)
  109.824 ms (114179 allocations: 4.78 MiB)
  124.340 ms (167839 allocations: 6.89 MiB)
  132.645 ms (213391 allocations: 8.71 MiB)
  141.765 ms (257701 allocations: 10.49 MiB)
  155.150 ms (300755 allocations: 12.23 MiB)
  163.322 ms (342559 allocations: 13.86 MiB)
```

**Comment by wsmoses** [comment]
this is fixed locally with https://github.com/EnzymeAD/Reactant.jl/pull/326 and latest Enzyme. Note that this still indicates Enzyme.jl's interpreter rule stuff is being sad, but we can disable rules

```
julia> for _ in 1:100
            @btime Reactant.with_debug() do
                 @jit Reactant.Ops.abs(x)
            end
       end
  227.179 ms (14440 allocations: 1012.28 KiB)
  227.738 ms (14440 allocations: 1012.28 KiB)
  227.988 ms (14440 allocations: 1012.28 KiB)
  229.066 ms (14440 allocations: 1012.28 KiB)
  229.683 ms (14440 allocations: 1012.28 KiB)
  231.294 ms (14440 allocations: 1012.28 KiB)
  232.302 ms (14440 allocations: 1012.28 KiB)
  233.247 ms (14440 allocations: 1012.28 KiB)
  233.694 ms (14440 allocations: 1012.28 KiB)
  234.768 ms (14440 allocations: 1012.28 KiB)
  235.695 ms (14440 allocations: 1012.28 KiB)
  237.790 ms (14440 allocations: 1012.28 KiB)
  238.352 ms (14440 allocations: 1012.28 KiB)
  239.087 ms (14440 allocations: 1012.28 KiB)
  240.611 ms (14440 allocations: 1012.28 KiB)
  241.681 ms (14440 allocations: 1012.28 KiB)
  241.488 ms (14440 allocations: 1012.28 KiB)
  242.259 ms (14440 allocations: 1012.28 KiB)
  242.878 ms (14440 allocations: 1012.28 KiB)
  243.833 ms (14440 allocations: 1012.28 KiB)
```

**Comment by wsmoses** [comment]
time does climb a bit tho weirdly

**Comment by jumerckx** [comment]
With the latest interpreter stuff, increasing times (not allocations) are still a thing.
```
julia> for _ in 1:100
            @btime Reactant.Ops.with_debug() do
                 @jit Reactant.Ops.abs(x)
            end
       end
  62.994 ms (10989 allocations: 535.89 KiB)
  64.359 ms (10989 allocations: 535.89 KiB)
  66.648 ms (10989 allocations: 535.89 KiB)
  69.255 ms (10989 allocations: 535.89 KiB)
  70.272 ms (10989 allocations: 535.89 KiB)
  70.745 ms (10989 allocations: 535.89 KiB)
  71.283 ms (10989 allocations: 535.89 KiB)
  72.623 ms (10989 allocations: 535.89 KiB)
  73.641 ms (10989 allocations: 535.89 KiB)
  76.192 ms (10989 allocations: 535.89 KiB)
  77.077 ms (10989 allocations: 535.89 KiB)
  78.479 ms (10989 allocations: 535.89 KiB)
  80.126 ms (10989 allocations: 535.89 KiB)
```

**Comment by mofeing** [comment]
yeah, but the scaling is much lower

```julia
julia> for _ in 1:10
           @btime @jit Ops.abs(x)
       end
  15.026 ms (10978 allocations: 535.72 KiB)
  15.111 ms (10978 allocations: 535.72 KiB)
  16.605 ms (10978 allocations: 535.72 KiB)
  16.844 ms (10978 allocations: 535.72 KiB)
  18.649 ms (10978 allocations: 535.72 KiB)
  19.280 ms (10978 allocations: 535.72 KiB)
  19.619 ms (10978 allocations: 535.72 KiB)
  19.835 ms (10978 allocations: 535.72 KiB)
  20.569 ms (10978 allocations: 535.72 KiB)
  22.509 ms (10978 allocations: 535.72 KiB)

julia> for _ in 1:10
           @btime Ops.with_debug() do
               @jit Ops.abs(x)
           end
       end
  25.965 ms (11814 allocations: 583.87 KiB)
  26.740 ms (11814 allocations: 583.87 KiB)
  27.133 ms (11814 allocations: 583.87 KiB)
  27.839 ms (11814 allocations: 583.87 KiB)
  28.385 ms (11814 allocations: 583.87 KiB)
  29.134 ms (11814 allocations: 583.87 KiB)
  29.415 ms (11814 allocations: 583.87 KiB)
  30.080 ms (11814 allocations: 583.87 KiB)
  30.586 ms (11814 allocations: 583.87 KiB)
  31.217 ms (11814 allocations: 583.87 KiB)
```

**Comment by mofeing** [comment]
As of Reactant 0.2.189 and Julia 1.12.3, this issue still remains:

```julia
29.610 ms (1929 allocations: 757.58 KiB)
  30.858 ms (1929 allocations: 757.58 KiB)
  34.103 ms (1929 allocations: 757.58 KiB)
  33.578 ms (1929 allocations: 757.58 KiB)
  40.554 ms (1929 allocations: 757.58 KiB)
  39.912 ms (1929 allocations: 757.58 KiB)
  40.570 ms (1929 allocations: 757.58 KiB)
  39.753 ms (1929 allocations: 757.58 KiB)
  38.856 ms (1929 allocations: 757.58 KiB)
  49.652 ms (1929 allocations: 757.58 KiB)
  50.318 ms (1929 allocations: 757.58 KiB)
  51.032 ms (1929 allocations: 757.58 KiB)
  52.274 ms (1929 allocations: 757.58 KiB)
  52.350 ms (1929 allocations: 757.58 KiB)
  53.457 ms (1929 allocations: 757.58 KiB)
  53.116 ms (1929 allocations: 757.58 KiB)
  53.747 ms (1929 allocations: 757.58 KiB)
  53.886 ms (1929 allocations: 757.58 KiB)
  54.117 ms (1929 allocations: 757.58 KiB)
  54.630 ms (1929 allocations: 757.58 KiB)
  55.022 ms (1929 allocations: 757.58 KiB)
  55.706 ms (1929 allocations: 757.58 KiB)
  55.867 ms (1929 allocations: 757.58 KiB)
  56.725 ms (1929 allocations: 757.58 KiB)
  70.436 ms (1929 allocations: 757.58 KiB)
  71.412 ms (1929 allocations: 757.58 KiB)
  72.489 ms (1929 allocations: 757.58 KiB)
  73.572 ms (1929 allocations: 757.58 KiB)
  74.393 ms (1929 allocations: 757.58 KiB)
  75.432 ms (1929 allocations: 757.58 KiB)
  75.852 ms (1929 allocations: 757.58 KiB)
  75.717 ms (1929 allocations: 757.58 KiB)
  77.422 ms (1929 allocations: 757.58 KiB)
  77.396 ms (1929 allocations: 757.58 KiB)
  78.448 ms (1929 allocations: 757.58 KiB)
  79.899 ms (1929 allocations: 757.58 KiB)
  81.038 ms (1929 allocations: 757.58 KiB)
  80.343 ms (1929 allocations: 757.58 KiB)
  80.370 ms (1929 allocations: 757.58 KiB)
  80.852 ms (1929 allocations: 757.58 KiB)
  80.395 ms (1929 allocations: 757.58 KiB)
  82.481 ms (1929 allocations: 757.58 KiB)
  81.625 ms (1929 allocations: 757.58 KiB)
  84.459 ms (1929 allocations: 757.58 KiB)
  83.459 ms (1929 allocations: 757.58 KiB)
  83.614 ms (1929 allocations: 757.58 KiB)
  85.656 ms (1929 allocations: 757.58 KiB)
  85.208 ms (1929 allocations: 757.58 KiB)
  85.571 ms (1929 allocations: 757.58 KiB)
julia(70542,0x203f18800) malloc: Failed to allocate segment from range group - out of space
  86.646 ms (1929 allocations: 757.58 KiB)
  86.811 ms (1929 allocations: 757.58 KiB)
  88.700 ms (1929 allocations: 757.58 KiB)
  86.935 ms (1929 allocations: 757.58 KiB)
  89.900 ms (1929 allocations: 757.58 KiB)
  89.684 ms (1929 allocations: 757.58 KiB)
  89.988 ms (1929 allocations: 757.58 KiB)
  88.841 ms (1929 allocations: 757.58 KiB)
  89.957 ms (1929 allocations: 757.58 KiB)
  91.017 ms (1929 allocations: 757.58 KiB)
  91.622 ms (1929 allocations: 757.58 KiB)
```

**Comment by mofeing** [comment]
some more in depth info: I've profiled `@compile` every time the benchmarked time passed a certain threshold (the bold text in the header) and there are some functions that are clearly increasing their time.

in particular, the ones that are increasing their time are:
- **context creation** (`mlirContextCreateWithRegistry`) goes from **1%** to **16%** of the runtime
- **type creation within a context** (attributes types, function types, array types, ...), make `make_mlir_fn` go from **2%** to **20%**

<img width="1097" height="384" alt="Image" src="https://github.com/user-attachments/assets/a190ee60-9b3a-4a10-a341-51d0ece55eca" />

passes are the current bottleneck (`mlirPassManagerRunOnOp`) so that's taken as the reference.

mmm since we are creating so many `Context`s... could it be that we are not correctly freeing them? or does MLIR hold some kind of reference that makes `Context` heavier to use?

ps: sorry, I didn't notice I was using the Spanish comma notation

**Comment by wsmoses** [comment]
I at least partially see something for the context. we create it here: https://github.com/EnzymeAD/Reactant.jl/blob/10d5db4a9d76a9373f44c6d36a92fb54e82b89f6/src/TracedUtils.jl#L898. However, it's not obvious that the context is unnecessary by the end of the function. Ironically in fact the very opposite is true since we're clearly returning funcops and the like which depend on the context. 

So probably instead of rely on Julia GC to eventually call finalize, we should figure out when we dont actually need the context anymore and free it ourselves. That likely would have subsequent impacts on the rest of these?

**Comment by mofeing** [comment]
checking the ["Context.jl"](https://github.com/EnzymeAD/Reactant.jl/blob/715202e239d41dc880f8d385f0915f3e54c235f7/src/mlir/IR/Context.jl) file, I just noticed that there is no way to call the destructor...

the Julia GC just forgets the pointer but [`mlirContextDestroy`](https://github.com/EnzymeAD/Reactant.jl/blob/715202e239d41dc880f8d385f0915f3e54c235f7/src/mlir/libMLIR_h.jl#L373) is never called.

we should probably make `Context` mutable and make the finalizer call `dispose!`

**Comment by mofeing** [comment]
i've revamped the `Context` implementation to finalize if the context object is owned and changed the `task_local_storage` for a `ScopedValue`. the result is that the compile times (i.e. runtime of `@compile`) no longer increases!

```
julia> for _ in 1:40 @btime(@compile(Reactant.Ops.abs(x)),setup=(GC.gc())) end
  29.453 ms (1901 allocations: 758.61 KiB)
  29.525 ms (1901 allocations: 758.61 KiB)
  29.464 ms (1901 allocations: 758.61 KiB)
  29.445 ms (1901 allocations: 758.61 KiB)
  29.490 ms (1901 allocations: 758.61 KiB)
  29.403 ms (1901 allocations: 758.61 KiB)
  29.561 ms (1901 allocations: 758.61 KiB)
  29.523 ms (1901 allocations: 758.61 KiB)
  29.567 ms (1901 allocations: 758.61 KiB)
  29.545 ms (1901 allocations: 758.61 KiB)
  29.456 ms (1901 allocations: 758.61 KiB)
  29.432 ms (1901 allocations: 758.61 KiB)
  29.308 ms (1901 allocations: 758.61 KiB)
  29.396 ms (1901 allocations: 758.61 KiB)
  29.437 ms (1901 allocations: 758.61 KiB)
  29.367 ms (1901 allocations: 758.61 KiB)
  29.339 ms (1901 allocations: 758.61 KiB)
  29.331 ms (1901 allocations: 758.61 KiB)
  29.481 ms (1901 allocations: 758.61 KiB)
  29.516 ms (1901 allocations: 758.61 KiB)
  29.659 ms (1901 allocations: 758.61 KiB)
  29.464 ms (1901 allocations: 758.61 KiB)
  29.521 ms (1901 allocations: 758.61 KiB)
  29.814 ms (1901 allocations: 758.61 KiB)
  29.600 ms (1901 allocations: 758.61 KiB)
  29.436 ms (1901 allocations: 758.61 KiB)
  29.596 ms (1901 allocations: 758.61 KiB)
  29.507 ms (1901 allocations: 758.61 KiB)
  29.651 ms (1901 allocations: 758.61 KiB)
  29.654 ms (1901 allocations: 758.61 KiB)
  29.374 ms (1901 allocations: 758.61 KiB)
  29.588 ms (1901 allocations: 758.61 KiB)
  29.371 ms (1901 allocations: 758.61 KiB)
  29.509 ms (1901 allocations: 758.61 KiB)
  29.607 ms (1901 allocations: 758.61 KiB)
  29.595 ms (1901 allocations: 758.61 KiB)
  29.418 ms (1901 allocations: 758.61 KiB)
  29.529 ms (1901 allocations: 758.61 KiB)
  29.429 ms (1901 allocations: 758.61 KiB)
  29.462 ms (1901 allocations: 758.61 KiB)

julia> for _ in 1:20 @btime(@compile(Reactant.Ops.abs(x))) end
  29.018 ms (1901 allocations: 758.61 KiB)
  28.852 ms (1901 allocations: 758.61 KiB)
  30.579 ms (1901 allocations: 758.61 KiB)
  29.291 ms (1901 allocations: 758.61 KiB)
  28.953 ms (1901 allocations: 758.61 KiB)
  29.025 ms (1901 allocations: 758.61 KiB)
  28.858 ms (1901 allocations: 758.61 KiB)
  28.723 ms (1901 allocations: 758.61 KiB)
  28.839 ms (1901 allocations: 758.61 KiB)
  28.890 ms (1901 allocations: 758.61 KiB)
  28.737 ms (1901 allocations: 758.61 KiB)
  28.828 ms (1901 allocations: 758.61 KiB)
  28.875 ms (1901 allocations: 758.61 KiB)
  28.804 ms (1901 allocations: 758.61 KiB)
  28.908 ms (1901 allocations: 758.61 KiB)
  28.898 ms (1901 allocations: 758.61 KiB)
  28.845 ms (1901 allocations: 758.61 KiB)
  28.979 ms (1901 allocations: 758.61 KiB)
  28.927 ms (1901 allocations: 758.61 KiB)
  28.857 ms (1901 allocations: 758.61 KiB)
```

**Comment by mofeing** [comment]
finally fixed in #2365 (plus little fix in #2414). these are the results in hydra:

<img width="563" height="399" alt="Image" src="https://github.com/user-attachments/assets/68c52799-c111-4d4b-87d4-a4e6b8578a4b" />
