### ISSUE TITLE
Int32 Array compiling got AssertionError: ElType != Any && ElType != Union{}

### ISSUE THREAD

**Issue by x66ccff** [EnzymeAD/Reactant.jl#470]
# Code

```julia
using Reactant

const T_kernel_compiling_idx = Int32  #  Int64: ✔ pass, Int32: ❌ fail

function get_triu_indices(n::Int)
    num_indices = n * (n + 1) ÷ 2
    indices_matrix = Matrix{T_kernel_compiling_idx}(undef, num_indices, 2)
    idx = 1
    for i in 1:n
        for j in i:n
            indices_matrix[idx, 1] = i
            indices_matrix[idx, 2] = j
            idx += 1
        end
    end
    return collect(transpose(indices_matrix))
end

function add_kernel!(x::AbstractMatrix, n::Int, indices::AbstractMatrix)
    l_idx = indices[1, :]
    r_idx = indices[2, :]
    l_value = x[l_idx]'
    r_value = x[r_idx]'
    res = l_value .+ r_value
    return res
end

function compile_binary_triu_kernel(input_dim::Int, func::Function)
    n = input_dim
    x = rand(Float32, 1, n)
    xr = Reactant.to_rarray(x)

    triu = get_triu_indices(n)
    triur = Reactant.to_rarray(triu)

    compiled_func = @compile func(xr, n, triur)
    
    return compiled_func
end

@info "⚠compiling for T = $T_kernel_compiling_idx "
compiled_add_kernel = compile_binary_triu_kernel(5, add_kernel!)
@info "success!"

```

# Outputs

```bash
1-element ExceptionStack:
AssertionError: ElType != Any && ElType != Union{}
Stacktrace:
  [1] copy
    @ ~/.julia/packages/Reactant/7m11i/src/TracedRArray.jl:437 [inlined]
  [2] copy(none::Base.Broadcast.Broadcasted{Reactant.TracedRArrayOverrides.AbstractReactantArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(rem), Tuple{Reactant.TracedRArray{Int64, 1}, Reactant.TracedRNumber{Int32}}})
    @ Reactant ./<missing>:0
  [3] call_with_reactant(::typeof(copy), ::Base.Broadcast.Broadcasted{Reactant.TracedRArrayOverrides.AbstractReactantArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(rem), Tuple{Reactant.TracedRArray{Int64, 1}, Reactant.TracedRNumber{Int32}}})
    @ Reactant ~/.julia/packages/Reactant/7m11i/src/utils.jl:530
  [4] materialize
    @ ./broadcast.jl:867 [inlined]
  [5] scalar_index_to_cartesian
    @ ~/.julia/packages/Reactant/7m11i/src/TracedRArray.jl:80 [inlined]
  [6] scalar_index_to_cartesian(none::Reactant.TracedRArray{Int32, 1}, none::Tuple{Int64, Int64})
    @ Reactant ./<missing>:0
  [7] broadcasted
    @ ./broadcast.jl:1328 [inlined]
  [8] broadcasted
    @ ./broadcast.jl:1326 [inlined]
  [9] scalar_index_to_cartesian
    @ ~/.julia/packages/Reactant/7m11i/src/TracedRArray.jl:79 [inlined]
 [10] call_with_reactant(::typeof(Reactant.TracedRArrayOverrides.scalar_index_to_cartesian), ::Reactant.TracedRArray{Int32, 1}, ::Tuple{Int64, Int64})
    @ Reactant ~/.julia/packages/Reactant/7m11i/src/utils.jl:0
 [11] getindex
    @ ~/.julia/packages/Reactant/7m11i/src/TracedRArray.jl:103 [inlined]
 [12] getindex(none::Reactant.TracedRArray{Float32, 2}, none::Reactant.TracedRArray{Int32, 1})
    @ Reactant ./<missing>:0
 [13] call_with_reactant(::typeof(getindex), ::Reactant.TracedRArray{Float32, 2}, ::Reactant.TracedRArray{Int32, 1})
    @ Reactant ~/.julia/packages/Reactant/7m11i/src/utils.jl:530
 [14] add_kernel!
    @ ./REPL[4]:4 [inlined]
 [15] add_kernel!(none::Reactant.TracedRArray{Float32, 2}, none::Int64, none::Reactant.TracedRArray{Int32, 2})
    @ Reactant ./<missing>:0
 [16] add_kernel!
    @ ./REPL[4]:2 [inlined]
 [17] call_with_reactant(::typeof(add_kernel!), ::Reactant.TracedRArray{Float32, 2}, ::Int64, ::Reactant.TracedRArray{Int32, 2})
    @ Reactant ~/.julia/packages/Reactant/7m11i/src/utils.jl:0
 [18] (::Reactant.TracedUtils.var"#8#18"{Bool, Bool, typeof(add_kernel!), Tuple{ConcreteRArray{Float32, 2}, Int64, ConcreteRArray{Int32, 2}}, Vector{Union{ReactantCore.MissingTracedValue, Reactant.TracedRArray, Reactant.TracedRNumber}}, Tuple{Reactant.TracedRArray{Float32, 2}, Int64, Reactant.TracedRArray{Int32, 2}}})()
    @ Reactant.TracedUtils ~/.julia/packages/Reactant/7m11i/src/TracedUtils.jl:182
 [19] block!(f::Reactant.TracedUtils.var"#8#18"{Bool, Bool, typeof(add_kernel!), Tuple{ConcreteRArray{Float32, 2}, Int64, ConcreteRArray{Int32, 2}}, Vector{Union{ReactantCore.MissingTracedValue, Reactant.TracedRArray, Reactant.TracedRNumber}}, Tuple{Reactant.TracedRArray{Float32, 2}, Int64, Reactant.TracedRArray{Int32, 2}}}, blk::Reactant.MLIR.IR.Block)
    @ Reactant.MLIR.IR ~/.julia/packages/Reactant/7m11i/src/mlir/IR/Block.jl:201
 [20] make_mlir_fn(f::Function, args::Tuple{ConcreteRArray{Float32, 2}, Int64, ConcreteRArray{Int32, 2}}, kwargs::Tuple{}, name::String, concretein::Bool; toscalar::Bool, return_dialect::Symbol, no_args_in_result::Bool, construct_function_without_args::Bool, do_transpose::Bool)
    @ Reactant.TracedUtils ~/.julia/packages/Reactant/7m11i/src/TracedUtils.jl:169
 [21] make_mlir_fn
    @ ~/.julia/packages/Reactant/7m11i/src/TracedUtils.jl:86 [inlined]
 [22] #10
    @ ~/.julia/packages/Reactant/7m11i/src/Compiler.jl:330 [inlined]
 [23] block!(f::Reactant.Compiler.var"#10#15"{typeof(add_kernel!), Tuple{ConcreteRArray{Float32, 2}, Int64, ConcreteRArray{Int32, 2}}}, blk::Reactant.MLIR.IR.Block)
    @ Reactant.MLIR.IR ~/.julia/packages/Reactant/7m11i/src/mlir/IR/Block.jl:201
 [24] #9
    @ ~/.julia/packages/Reactant/7m11i/src/Compiler.jl:329 [inlined]
 [25] mmodule!(f::Reactant.Compiler.var"#9#14"{Reactant.MLIR.IR.Module, typeof(add_kernel!), Tuple{ConcreteRArray{Float32, 2}, Int64, ConcreteRArray{Int32, 2}}}, blk::Reactant.MLIR.IR.Module)
    @ Reactant.MLIR.IR ~/.julia/packages/Reactant/7m11i/src/mlir/IR/Module.jl:92
 [26] compile_mlir!(mod::Reactant.MLIR.IR.Module, f::Function, args::Tuple{ConcreteRArray{Float32, 2}, Int64, ConcreteRArray{Int32, 2}}; optimize::Bool)
    @ Reactant.Compiler ~/.julia/packages/Reactant/7m11i/src/Compiler.jl:326
 [27] compile_mlir!
    @ ~/.julia/packages/Reactant/7m11i/src/Compiler.jl:325 [inlined]
 [28] (::Reactant.Compiler.var"#32#34"{Bool, typeof(add_kernel!), Tuple{ConcreteRArray{Float32, 2}, Int64, ConcreteRArray{Int32, 2}}})()
    @ Reactant.Compiler ~/.julia/packages/Reactant/7m11i/src/Compiler.jl:820
 [29] context!(f::Reactant.Compiler.var"#32#34"{Bool, typeof(add_kernel!), Tuple{ConcreteRArray{Float32, 2}, Int64, ConcreteRArray{Int32, 2}}}, ctx::Reactant.MLIR.IR.Context)
    @ Reactant.MLIR.IR ~/.julia/packages/Reactant/7m11i/src/mlir/IR/Context.jl:76
 [30] compile_xla(f::Function, args::Tuple{ConcreteRArray{Float32, 2}, Int64, ConcreteRArray{Int32, 2}}; client::Nothing, optimize::Bool)
    @ Reactant.Compiler ~/.julia/packages/Reactant/7m11i/src/Compiler.jl:817
 [31] compile_xla
    @ ~/.julia/packages/Reactant/7m11i/src/Compiler.jl:812 [inlined]
 [32] compile(f::Function, args::Tuple{ConcreteRArray{Float32, 2}, Int64, ConcreteRArray{Int32, 2}}; client::Nothing, optimize::Bool, sync::Bool)
    @ Reactant.Compiler ~/.julia/packages/Reactant/7m11i/src/Compiler.jl:844
 [33] compile
    @ ~/.julia/packages/Reactant/7m11i/src/Compiler.jl:843 [inlined]
 [34] macro expansion
    @ ~/.julia/packages/Reactant/7m11i/src/Compiler.jl:557 [inlined]
 [35] compile_binary_triu_kernel(input_dim::Int64, func::Function)
    @ Main ./REPL[5]:9
 [36] top-level scope
    @ REPL[7]:1
```

**Comment by mofeing** [comment]
The error seems to originate in this line:
```
copy(none::Base.Broadcast.Broadcasted{Reactant.TracedRArrayOverrides.AbstractReactantArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(rem), Tuple{Reactant.TracedRArray{Int64, 1}, Reactant.TracedRNumber{Int32}}})
```

If you look closely, it seems like the erroring code is on `rem.(A,B)` where `A` is a `TracedRArray{Int64, 1}` and `B` is a `TracedRNumber{Int32}`.

I can reproduce the error with this code:
```julia
A = [1, 5, 11, 17]
B = 7
Are = Reactant.to_rarray(A)
Bre = Reactant.to_rarray(B)
@jit rem.(A,B)
```

**Comment by wsmoses** [comment]
I think the solution here is to just extend the rem (and perhaps other) functions to support inputs of different types by first promoting them to a common eltype.

@x66ccff do you want to try to give that a go?

**Comment by x66ccff** [comment]
Thanks for the suggestion! I can try working on this tomorrow, though I'm still fairly new to Julia 😂

**Comment by mofeing** [comment]
One question i have is whether we should treat `Broadcasted` as a wrapped array. do you have any opinion @avik-pal ?

**Comment by x66ccff** [comment]
@mofeing hey, but this code runs with no error in my machine


```bash
(base) kent@kent-Super-Server:~/_Project/Reactant.jl/Reactant.jl$ julia --project=.
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.1 (2024-10-16)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using Reactant

julia> A = [1, 5, 11, 17]
4-element Vector{Int64}:
  1
  5
 11
 17

julia> B = 7
7

julia> Are = Reactant.to_rarray(A)
4-element ConcreteRArray{Int64, 1}:
  1
  5
 11
 17

julia> Bre = Reactant.to_rarray(B)
7

julia> @jit rem.(A,B)
2025-01-05 10:16:18.232628: I external/xla/xla/service/llvm_ir/llvm_command_line_options.cc:50] XLA (re)initializing LLVM with options fingerprint: 16826357586686331175
4-element Vector{Int64}:
 1
 5
 4
 3

julia> 
```

**Comment by x66ccff** [comment]
Sorry - totally messed up, I'm clueless about Julia 😵 Can someone else take this PR?

**Comment by mofeing** [comment]
ups my bad, copy-pasted too fast. i've fixed the typos you said in the code above, but there's one more missing: `B` has to be a `Int32`, so you need to do
```julia
B = Int32(7)
```

**Comment by mofeing** [comment]
@wsmoses @avik-pal how about overlaying `Base.materialize` on `Broadcasted`?

**Comment by wsmoses** [comment]
Is this fixable without an overload? We should use those sparingly because since we're doing things post type inference, if there's a change to return types or whether an error is thrown its possible to introduce undefined behavior/segfaults

**Comment by wsmoses** [comment]
Okay this PR https://github.com/EnzymeAD/Reactant.jl/pull/476 will improve the error message so you can actually see what's going on.

With that in place, here's the actual error (which is simple enough to fix if you want to give it a go).

```julia
ERROR: MethodError: no method matching rem(::Reactant.TracedRNumber{Int64}, ::Int64)

Closest candidates are:
  rem(::Any, ::Any, ::RoundingMode{:FromZero})
   @ Base div.jl:103
  rem(::Any, ::Any, ::RoundingMode{:Nearest})
   @ Base div.jl:100
  rem(::Any, ::Any, ::RoundingMode{:Up})
   @ Base div.jl:99
  ...

Stacktrace:
  [1] macro expansion
    @ ~/git/Reactant.jl/src/utils.jl:0 [inlined]
  [2] call_with_reactant(::typeof(rem), ::Reactant.TracedRNumber{Int64}, ::Int64)
    @ Reactant ~/git/Reactant.jl/src/utils.jl:583
  [3] copy
    @ ~/git/Reactant.jl/src/TracedRArray.jl:456 [inlined]
  [4] copy(none::Base.Broadcast.Broadcasted{Reactant.TracedRArrayOverrides.AbstractReactantArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(rem), Tuple{Reactant.TracedRArray{Int64, 1}, Int64}})
    @ Reactant ./<missing>:0
  [5] copy
    @ ~/git/Reactant.jl/src/TracedRArray.jl:448 [inlined]
  [6] call_with_reactant(::typeof(copy), ::Base.Broadcast.Broadcasted{Reactant.TracedRArrayOverrides.AbstractReactantArrayStyle{1}, Tuple{Base.OneTo{Int64}}, typeof(rem), Tuple{Reactant.TracedRArray{Int64, 1}, Int64}})
    @ Reactant ~/git/Reactant.jl/src/utils.jl:0
  [7] materialize
    @ ./broadcast.jl:903 [inlined]
  [8] BroadcastFunction
    @ ./broadcast.jl:1381 [inlined]
  [9] (::Base.Broadcast.BroadcastFunction{typeof(rem)})(none::Tuple{Reactant.TracedRArray{Int64, 1}, Int64})
    @ Reactant ./<missing>:0
 [10] BroadcastFunction
    @ ./broadcast.jl:1381 [inlined]
 [11] call_with_reactant(::Base.Broadcast.BroadcastFunction{typeof(rem)}, ::Reactant.TracedRArray{Int64, 1}, ::Int64)
    @ Reactant ~/git/Reactant.jl/src/utils.jl:0
 [12] #apply#23
    @ ~/git/Reactant.jl/src/utils.jl:3 [inlined]
 [13] var"#apply#23"(none::@Kwargs{}, none::typeof(Reactant.apply), none::Function, none::Tuple{Reactant.TracedRArray{Int64, 1}, Any})
    @ Reactant ./<missing>:0
 [14] call_with_reactant(::Reactant.var"##apply#23", ::@Kwargs{}, ::typeof(Reactant.apply), ::Function, ::Reactant.TracedRArray{Int64, 1}, ::Any)
    @ Reactant ~/git/Reactant.jl/src/utils.jl:3
 [15] apply
    @ ~/git/Reactant.jl/src/utils.jl:2 [inlined]
 [16] apply(none::Base.Broadcast.BroadcastFunction{typeof(rem)}, none::Tuple{Reactant.TracedRArray{Int64, 1}, Int64})
    @ Reactant ./<missing>:0
 [17] call_with_reactant(::typeof(Reactant.apply), ::Base.Broadcast.BroadcastFunction{typeof(rem)}, ::Reactant.TracedRArray{Int64, 1}, ::Int64)
    @ Reactant ~/git/Reactant.jl/src/utils.jl:2
 [18] make_mlir_fn(f::Function, args::Tuple{…}, kwargs::Tuple{}, name::String, concretein::Bool; toscalar::Bool, return_dialect::Symbol, no_args_in_result::Bool, construct_function_without_args::Bool, do_transpose::Bool)
    @ Reactant.TracedUtils ~/git/Reactant.jl/src/TracedUtils.jl:184
 [19] make_mlir_fn(f::Function, args::Tuple{ConcreteRArray{Int64, 1}, Int64}, kwargs::Tuple{}, name::String, concretein::Bool; toscalar::Bool, return_dialect::Symbol, no_args_in_result::Bool, construct_function_without_args::Bool, do_transpose::Bool)
    @ Reactant.TracedUtils ~/git/Reactant.jl/src/TracedUtils.jl:99
 [20] make_mlir_fn
    @ ~/git/Reactant.jl/src/TracedUtils.jl:86 [inlined]
 [21] compile_mlir!(mod::Reactant.MLIR.IR.Module, f::Function, args::Tuple{ConcreteRArray{Int64, 1}, Int64}; optimize::Bool, no_nan::Bool)
    @ Reactant.Compiler ~/git/Reactant.jl/src/Compiler.jl:348
 [22] compile_mlir!
    @ ~/git/Reactant.jl/src/Compiler.jl:339 [inlined]
 [23] compile_xla(f::Function, args::Tuple{ConcreteRArray{Int64, 1}, Int64}; client::Nothing, optimize::Bool, no_nan::Bool)
    @ Reactant.Compiler ~/git/Reactant.jl/src/Compiler.jl:844
 [24] compile_xla
    @ ~/git/Reactant.jl/src/Compiler.jl:835 [inlined]
 [25] compile(f::Function, args::Tuple{ConcreteRArray{Int64, 1}, Int64}; client::Nothing, optimize::Bool, sync::Bool, no_nan::Bool)
    @ Reactant.Compiler ~/git/Reactant.jl/src/Compiler.jl:870
 [26] top-level scope
    @ ~/git/Reactant.jl/src/Compiler.jl:580
Some type information was truncated. Use `show(err)` to see complete types.
```

**Comment by wsmoses** [comment]
With a couple more things merged, we get to the following:

```julia
julia> @jit rem(ConcreteRNumber(0), ConcreteRNumber(Int32(3)))
ERROR: MethodError: no method matching rem(::Reactant.TracedRNumber{Int64}, ::Reactant.TracedRNumber{Int32})

Closest candidates are:
  rem(::Any, ::Any, ::RoundingMode{:FromZero})
   @ Base div.jl:103
  rem(::Any, ::Any, ::RoundingMode{:Nearest})
   @ Base div.jl:100
  rem(::Any, ::Any, ::RoundingMode{:Up})
   @ Base div.jl:99
  ...
```

However I'm not a bit confused why promotion doesn't resolve this

@avik-pal do you have any ideas?

**Comment by avik-pal** [comment]
```mlir
julia> @code_hlo add_kernel!(xr, n, triur)
module @reactant_add_ker... attributes {mhlo.num_partitions = 1 : i64, mhlo.num_replicas = 1 : i64} {
  func.func @main(%arg0: tensor<5x1xf32> {enzymexla.memory_effects = []}, %arg1: tensor<15x2xi32> {enzymexla.memory_effects = []}) -> tensor<15x1xf32> attributes {enzymexla.memory_effects = []} {
    %c = stablehlo.constant dense<1> : tensor<15x2xi32>
    %c_0 = stablehlo.constant dense<0> : tensor<i32>
    %c_1 = stablehlo.constant dense<5> : tensor<15x1xi32>
    %c_2 = stablehlo.constant dense<[[1, 5], [1, 5], [1, 5], [1, 5], [1, 5], [1, 5], [1, 5], [1, 5], [1, 5], [1, 5], [1, 5], [1, 5], [1, 5], [1, 5], [1, 5]]> : tensor<15x2xi32>
    %0 = stablehlo.reshape %arg0 : (tensor<5x1xf32>) -> tensor<1x5xf32>
    %1 = stablehlo.subtract %arg1, %c : tensor<15x2xi32>
    %2 = stablehlo.transpose %1, dims = [1, 0] : (tensor<15x2xi32>) -> tensor<2x15xi32>
    %3 = stablehlo.slice %2 [0:1, 0:15] : (tensor<2x15xi32>) -> tensor<1x15xi32>
    %4 = stablehlo.reshape %3 : (tensor<1x15xi32>) -> tensor<15xi32>
    %5 = stablehlo.slice %2 [1:2, 0:15] : (tensor<2x15xi32>) -> tensor<1x15xi32>
    %6 = stablehlo.broadcast_in_dim %4, dims = [0] : (tensor<15xi32>) -> tensor<15x2xi32>
    %7 = stablehlo.remainder %6, %c_2 : tensor<15x2xi32>
    %8 = "stablehlo.gather"(%0, %7) <{dimension_numbers = #stablehlo.gather<offset_dims = [0], collapsed_slice_dims = [0], start_index_map = [0, 1], index_vector_dim = 1>, indices_are_sorted = false, slice_sizes = array<i64: 1, 1>}> : (tensor<1x5xf32>, tensor<15x2xi32>) -> tensor<1x15xf32>
    %9 = stablehlo.reshape %5 : (tensor<1x15xi32>) -> tensor<15x1xi32>
    %10 = stablehlo.remainder %9, %c_1 : tensor<15x1xi32>
    %11 = stablehlo.pad %10, %c_0, low = [0, 1], high = [0, 0], interior = [0, 0] : (tensor<15x1xi32>, tensor<i32>) -> tensor<15x2xi32>
    %12 = "stablehlo.gather"(%0, %11) <{dimension_numbers = #stablehlo.gather<offset_dims = [0], collapsed_slice_dims = [0], start_index_map = [0, 1], index_vector_dim = 1>, indices_are_sorted = false, slice_sizes = array<i64: 1, 1>}> : (tensor<1x5xf32>, tensor<15x2xi32>) -> tensor<1x15xf32>
    %13 = stablehlo.add %8, %12 : tensor<1x15xf32>
    %14 = stablehlo.reshape %13 : (tensor<1x15xf32>) -> tensor<15x1xf32>
    return %14 : tensor<15x1xf32>
  }
}
```
